In [1]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np

Using TensorFlow backend.


In [4]:
df0 = pd.read_table("data.csv", sep=',', header=None)
df0

0     1     2      3  4
0    37.9  73.4  55.3    0.0  1
1    35.8  66.4  55.4    0.0  1
2    36.8  66.0  55.4   18.6  1
3    36.7  64.3  52.7    0.0  1
4    36.2  73.0  52.4    0.0  1
5    37.0  71.4  60.4    8.2  1
6    29.0  85.3  81.4  112.4  1
7    32.3  82.9  74.0    0.0  1
8    32.3  75.3  63.1   58.2  1
9    34.5  58.0  36.7    0.0  1
10   34.6  53.3  37.7    0.0  1
11   33.5  71.0  38.1    0.0  1
12   28.5  91.0  80.0  185.0  1
13   29.0  88.0  70.0   38.3  0
14   30.8  87.0  62.0   13.3  1
15   30.2  86.0  59.0   11.0  1
16   33.6  83.0  51.0    0.0  1
17   31.6  93.0  67.0   62.0  1
18   30.7  90.0  70.0   49.3  1
19   30.5  91.0  70.0   37.7  1
20   30.9  88.0  55.0    0.7  1
21   34.1  84.0  38.0    5.4  1
22   35.0  74.0  36.0    0.0  1
23   27.7  96.0  64.0   64.5  1
24   30.7  90.0  41.0    0.5  1
25   31.5  83.0  24.0    0.0  1
26   30.3  77.0  23.0    0.0  1
27   30.9  80.0  23.0    0.0  1
28   31.3  71.0  19.0    0.0  1
29   30.3  73.0  29.0    0.0  1
..    ...   ...   ...    ... ..
395  32.0  88.9  57.4    0.0  1
396  31.1  82.3  60.1    0.0  1
397  31.1  93.6  58.4    0.0  1
398  32.9  95.9  55.7    0.0  1
399  32.0  83.3  56.5    0.0  1
400  30.4  87.1  65.3    0.0  1
401  30.5  84.1  55.6    0.0  0
402  30.1  82.3  47.6    0.0  0
403  31.5  90.7  76.7   54.6  1
404  33.5  88.4  70.1   26.0  0
405  33.6  85.9  65.4   10.0  1
406  31.5  83.7  71.4   11.1  1
407  34.0  70.3  52.3    0.6  1
408  34.9  71.9  49.3    8.0  1
409  35.6  64.4  45.6    1.3  0
410  33.8  88.3  64.0   50.9  1
411  31.3  92.7  77.3   81.8  1
412  31.5  91.6  78.6   73.7  1
413  32.8  89.7  67.9   21.1  1
414  32.1  89.6  72.6   40.3  1
415  29.4  95.1  79.1   89.2  1
416  32.2  93.0  67.6   37.9  1
417  31.5  88.6  62.6    0.0  1
418  31.3  81.7  65.0    0.0  1
419  30.8  89.0  56.6    0.0  1
420  30.9  94.9  59.7    0.0  1
421  31.0  85.9  49.7    0.0  1
422  28.3  92.6  69.4  119.7  1
423  28.2  95.3  58.7    0.0  1
424  27.1  92.9  70.6   11.7  1

[425 rows x 5 columns]

In [5]:
X = df0[df0.columns[0:3]]
X = np.array(X)
Y = df0[df0.columns[3:4]]
Y = np.array(Y)
print(X,Y)

[[ 37.9  73.4  55.3]
 [ 35.8  66.4  55.4]
 [ 36.8  66.   55.4]
 ..., 
 [ 28.3  92.6  69.4]
 [ 28.2  95.3  58.7]
 [ 27.1  92.9  70.6]] [[  0.00000000e+00]
 [  0.00000000e+00]
 [  1.86000000e+01]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  8.20000000e+00]
 [  1.12400000e+02]
 [  0.00000000e+00]
 [  5.82000000e+01]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  1.85000000e+02]
 [  3.83000000e+01]
 [  1.33000000e+01]
 [  1.10000000e+01]
 [  0.00000000e+00]
 [  6.20000000e+01]
 [  4.93000000e+01]
 [  3.77000000e+01]
 [  7.00000000e-01]
 [  5.40000000e+00]
 [  0.00000000e+00]
 [  6.45000000e+01]
 [  5.00000000e-01]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  0.00000000e+00]
 [  3.95000000e+01]
 [  5.82000000e+01]
 [  8.33000000e+01]
 [  2.31900000e+02]
 [  1.59000000e+01]
 [  0.

In [6]:
from keras.layers import Dense, Activation
model = Sequential()
#model.add(Dense(units=64, input_dim=(12,)))
#model.add(Activation('relu'))
#model.add(Dense(units=12))
#model.add(Activation('softmax'))
model.add(Dense(12, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(12, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(12, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(12, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(12, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(8, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(8, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(8, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(8, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(8, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(8, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(8, input_dim=3, init='uniform', activation='relu'))
model.add(Dense(4, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


/home/divyam/machineLearning/projects/lib/python3.6/site-packages/ipykernel/__main__.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(12, input_dim=3, activation="relu", kernel_initializer="uniform")`
/home/divyam/machineLearning/projects/lib/python3.6/site-packages/ipykernel/__main__.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(12, input_dim=3, activation="relu", kernel_initializer="uniform")`
/home/divyam/machineLearning/projects/lib/python3.6/site-packages/ipykernel/__main__.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(12, input_dim=3, activation="relu", kernel_initializer="uniform")`
/home/divyam/machineLearning/projects/lib/python3.6/site-packages/ipykernel/__main__.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(12, input_dim=3, activation="relu", kernel_initializer="uniform")`
/home/divyam/machineLearning/projects/lib/python3.6/site-packages/ipykernel/__main__.py:11: UserWarning: Up

In [9]:
model.fit(X, Y, epochs=1, batch_size=

Epoch 1/1
425/425 [==============================] - 0s - loss: -0.1521 - acc: 0.0024         


In [8]:
scores = model.evaluate(X, Y)
print ("Accuracy: %.2f%%" %(scores[1]*100))

 32/425 [=>............................] - ETA: 0sAccuracy: 0.24%


In [94]:
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk


In [95]:
import json
from keras.models import model_from_json
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")
# evaluate loaded model on test data
loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
score = loaded_model.evaluate(X, Y, verbose=0)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

Loaded model from disk
acc: 5.26%


In [115]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
train_data_X = map(lambda X: [X], list(X[:-20]))
train_data_Y = list(Y[:-20])
test_data_X = map(lambda X: [X], list(X[-20:]))
test_data_Y = list(Y[-20:])

In [116]:
lm.fit(train_data_X,train_data_Y)

TypeError: float() argument must be a string or a number, not 'map'

In [110]:
lm.predict(X)

array([[  1.11759882],
       [  1.12986013],
       [ 13.86254324],
       [ 37.75923644],
       [ 34.27163666],
       [ 34.96669609],
       [ 55.94478795],
       [ 42.16338504],
       [ 37.29177638],
       [ 28.01601914],
       [ 17.00874396],
       [  1.47736919],
       [ -1.86575698],
       [ 34.39154635],
       [ 12.49690568],
       [ -4.17857597],
       [  1.14823143],
       [  0.67462007],
       [  1.14819013],
       [  9.37518626]])

In [113]:
import matplotlib.pyplot as plt
plt.scatter(X,Y)

ValueError: x and y must be the same size